---

- name: "Make /var/awslogs/state/ directory"
  file:
    path: /var/awslogs/state/
    state: directory
    mode: 0755

- name: "Configure AWS CloudWatch Logs Agent"
  template:
    src: etc/awslogs/awslogs.conf.j2
    dest: /etc/awslogs/awslogs.conf
    owner: root
    group: root
    mode: 0644
  register: cloudwatch_agent_config
  notify: restart awslogs service
