---

- name: "Insert Ugly Python Install Script"
  file:
    src: awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    state: file
    mode: 0550

- name: "Create /etc/awslogs (Debian)."
  file:
    path: /etc/awslogs
    state: directory
    mode: 755
