---

- name: "Insert Ugly Python Install Script"
  copy:
    src: awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: 0550
  register: cloudwatch_agent_script

- name: "Create /etc/awslogs"
  file:
    path: /etc/awslogs
    state: directory
    mode: 0755
