---

- name: "Get ec2 facts (Debian)."
  action: ec2_facts

- name: "Install AWS CloudWatch Logs Agent"
  shell:
    "python /tmp/awslogs-agent-setup.py \
     --non-interactive \
     --region {{ ansible_ec2_placement_region }} \
     --configfile /etc/awslogs/awslogs.conf"
  notify: restart awslogs service
  when: cloudwatch_agent_config|changed or cloudwatch_agent_script|changed

- name: "Override /etc/logrotate.d/awslogs"
  template:
    src: etc/logrotate.d/awslogs_debian.j2
    dest: /etc/logrotate.d/awslogs
    owner: root
    group: root
    mode: 0644
